apiVersion: apps/v1
kind: Deployment
metadata:
  name: claritas-app
  labels:
    app: claritas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: claritas
  template:
    metadata:
      labels:
        app: claritas
    spec:
      containers:
      - name: claritas-app
        image: europe-west2-docker.pkg.dev/claritas-457808/claritas-app/claritas-app:${GITHUB_SHA}
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: claritas-app-service
spec:
  selector:
    app: claritas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: claritas-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: <your-app-domain>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: claritas-app-service
            port:
              number: 80