apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: claritas
  labels: { app: keycloak }
  annotations:
    cloud.google.com/backend-config: '{"default":"keycloak-backendconfig"}'
spec:
  selector: { app: keycloak }
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
