apiVersion: v1
kind: Service
metadata:
  name: claritas-app
  namespace: claritas
  labels:
    app: claritas-app
spec:
  selector:
    app: claritas-app
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: claritas-app
  namespace: claritas
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: claritas-app
                port:
                  number: 80