apiVersion: v1
kind: ConfigMap
metadata:
  name: claritas-config
  namespace: claritas
data:
  # These can be overwritten by the pipeline step that upserts the ConfigMap.
  INSTANCE_CONNECTION_NAME: "claritas-457808:europe-west2:claritas-sql"
  DB_NAME: "claritas"
  DB_USER: "claritas_app"