apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-sa
  namespace: claritas
  annotations:
    iam.gke.io/gcp-service-account: claritas-sql-gsa@claritas-457808.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flyway-sa
  namespace: claritas
  annotations:
    iam.gke.io/gcp-service-account: claritas-sql-gsa@claritas-457808.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-sa
  namespace: claritas
  annotations:
    iam.gke.io/gcp-service-account: claritas-sql-gsa@claritas-457808.iam.gserviceaccount.com
