name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build Docker Image and Push to GCR
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 🔐 Authenticate to Google Cloud via OIDC
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/920949118609/locations/global/workloadIdentityPools/claritas-oidc-pool/providers/gh-provider"
          service_account: "terraform-github-oidc@claritas-457808.iam.gserviceaccount.com"

      - name: 🏗️ Build Docker image
        run: |
          echo "Building Docker image with tag: europe-west2-docker.pkg.dev/claritas-457808/claritas-app:${{ github.sha }}"
          docker build -t europe-west2-docker.pkg.dev/claritas-457808/claritas-app:${{ github.sha }} -f ./infra/docker/Dockerfile .

      - name: 🧐 Debug GitHub SHA
        run: |
          echo "GitHub SHA: ${{ github.sha }}"

      - name: Debug Docker images
        run: |
          echo "List of Docker images:"
          docker images

      - name: Configure Docker for Google Cloud Artifact Registry
        run: |
          echo "Configuring Docker to use Google Cloud credentials for Artifact Registry"
          gcloud auth configure-docker europe-west2-docker.pkg.dev --quiet  # Update this line for Artifact Registry
          echo "Authenticating with gcloud for Artifact Registry"
          gcloud auth list

      - name: 🖼️ Push Docker image to Artifact Registry
        run: |
          echo "Pushing Docker image to Artifact Registry: europe-west2-docker.pkg.dev/claritas-457808/claritas-app:${{ github.sha }}"
          echo "Docker push command: docker push europe-west2-docker.pkg.dev/claritas-457808/claritas-app:${{ github.sha }}"
          echo "docker push europe-west2-docker.pkg.dev/claritas-457808/claritas-app:${{ github.sha }}"
          docker push europe-west2-docker.pkg.dev/claritas-457808/claritas-app:${{ github.sha }}

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v3

      - name: 🔐 Authenticate to GKE with OIDC
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/920949118609/locations/global/workloadIdentityPools/claritas-oidc-pool/providers/gh-provider"
          service_account: "terraform-github-oidc@claritas-457808.iam.gserviceaccount.com"

      - name: Install GKE gcloud auth plugin
        run: |
            gcloud components install gke-gcloud-auth-plugin

      - name: 💻 Configure kubectl
        run: |
          echo "Getting GKE credentials for cluster claritas-cluster"
          gcloud container clusters get-credentials claritas-cluster --region europe-west2 --project claritas-457808

      - name: 📤 Apply Kubernetes deployment
        run: |
          echo "Setting image for deployment claritas-app to europe-west2-docker.pkg.dev/claritas-457808/claritas-app:${{ github.sha }}"
          kubectl set image deployment/claritas-app claritas-app=europe-west2-docker.pkg.dev/claritas-457808/claritas-app:${{ github.sha }}
          kubectl rollout status deployment/claritas-app